# Generated by Django 5.1.1 on 2024-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
