# Generated by Django 5.1.1 on 2024-12-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='gallery_images',
        ),
    ]
