# Generated by Django 5.1.1 on 2024-12-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_housegallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseGallery',
        ),
    ]
