# Generated by Django 5.1.1 on 2024-12-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_house_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='gallery_images',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_gallery/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='houses.house')),
            ],
        ),
    ]
